### ISSUE TITLE
How to revert changes brought by this script

### ISSUE THREAD

**Issue by YangHanlin** [diddledani/one-script-wsl2-systemd#15]
Is there a way to uninstall this script, i.e. to revert the changes (on both Windows and WSL sides) brought by this script? There is seemingly no separate uninstall script nor an `-Uninstall` option in `Install.ps1`. Are there any plans to add such feature?

**Comment by diddledani** [comment]
to uninstall on the Windows side, you need to delete the scheduled tasks (located in windows task scheduler, within its powershell folder), and uninstall Gpg4Win if you installed it. |If you used the custom kernel then you want to delete the line in `C:\Users\your-username\.wslconfig` that begins with `kernel=`. On the linux side delete the file `/etc/profile.d/00-wsl2-systemd.sh`and edit `/etc/wsl.conf` to delete the line that begins with `command=`.

**Comment by YangHanlin** [comment]
> to uninstall on the Windows side, you need to delete the scheduled tasks (located in windows task scheduler, within its powershell folder), and uninstall Gpg4Win if you installed it. |If you used the custom kernel then you want to delete the line in `C:\Users\your-username\.wslconfig` that begins with `kernel=`. On the linux side delete the file `/etc/profile.d/00-wsl2-systemd.sh`and edit `/etc/wsl.conf` to delete the line that begins with `command=`.

@diddledani Thanks for your kind reply!
