### ISSUE TITLE
error on each wsl start

### ISSUE THREAD

**Issue by mrt181** [diddledani/one-script-wsl2-systemd#20]
Thank you for this script.

It worked and I can install snap packages, great.

I observer one thing though.

Whenever I start wss.exe in windows terminal I get this message before my prompt appears.

```
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:32
+ Write-Output $Env:ProgramFiles(x86)
+                                ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

wslpath: /GnuPG/bin/gpg.exe
ln: failed to create symbolic link '/home/mrt181/.wsl-cmds/gpg' -> '': No such file or directory
```
I have created the link manually myself
`ln -s /mnt/c/Program\ Files\ \(x86\)/GnuPG/bin/gpg.exe gpg`

but the error persists on each start. It looks as if the gpg installation path needs to be escaped.

**Comment by diddledani** [comment]
This is a bug in WSLUtilities. We're waiting for @patrick330602 to create a new release of WSLu.

wslutilities/wslu#212
