### ISSUE TITLE
How do I make a unit (service) enable after I have made disable?

### ISSUE THREAD

**Issue by haosmos** [diddledani/one-script-wsl2-systemd#33]
I apologize if my question is not related to your wonderful script.

I installed your script and everything seems to work fine (there is one nuance, I asked this question in a separate post).

But shouldn't it be that when I run the command: 

systemctl disable <servise>

then afterwards I should also be able to make the unit available again by running the command

systemctl enable <servise>?

In my case, when I execute the command systemctl disable <service>, then after that I can not reactivate the unit.

![WindowsTerminal_fDsXaTKzWG](https://user-images.githubusercontent.com/30666874/170991185-a3942a6d-d4f7-47f0-9bc9-fcfad7ea4a41.png)

Or is this expected behavior of systemd and cannot be changed?

**Comment by diddledani** [comment]
The service is named `ssh.service` (no D). Your start and enable commands are failing because you used the wrong name.

**Comment by diddledani** [comment]
Hi, did this solve your problem?

**Comment by haosmos** [comment]
> Hi, did this solve your problem?

I apologize for the long response. Yes, thank you very much! ✌️
