### ISSUE TITLE
command not found: -zsh

### ISSUE THREAD

**Issue by joedborg** [diddledani/one-script-wsl2-systemd#6]
Following https://github.com/diddledan/one-script-wsl2-systemd/issues/5

Since that patch, I now see

```
/etc/profile.d/00-wsl2-systemd.sh:50: command not found: -zsh
```

When trying to open a WSL shell.

**Comment by diddledani** [comment]
Can you try again using the latest code in the `main` branch? I think this is fixed now.

**Comment by diddledani** [comment]
Closing old issue as I believe it's fixed. Please reopen if I'm wrong.
