### ISSUE TITLE
Interop seems broken after running script

### ISSUE THREAD

**Issue by joedborg** [diddledani/one-script-wsl2-systemd#7]
After running the script, I don't seem to be able to run any exe commands anymore:

```
➜ cmd.exe /c ver
<3>init: (1158) ERROR: UtilConnectToInteropServer:300: connect failed 2
```

```
➜ code .
<3>init: (1190) ERROR: UtilConnectToInteropServer:300: connect failed 2
```

**Comment by diddledan** [comment]
This is probably because you are using ZSH. The script sets up bash to reinstate the `$WSL_INTEROP` variable once you're logged in

**Comment by joedborg** [comment]
I'm not sure as it was working fine with https://github.com/damionGans/ubuntu-wsl2-systemd-script/ and I checked that `$WSL_INTEROP` was set and that the socket existed.  Maybe it's `basic.target` vs `multi-user.target`?

**Comment by joedborg** [comment]
I also re-ran the script after your changes a few hours ago.  The terminal now hangs and just eats memory (seemingly forever), not sure if this is expected for the first run or if there's a bug I should raise?

**Comment by joedborg** [comment]
Further to that, if I delete the profile and start a new sell, I can see a lot of zsh sessions, so I guess it's just creating them infinitely.

**Comment by diddledani** [comment]
Can you try again using the latest `install.ps1` from the `main` branch? There have been several improvements and I think this might be fixed now.

**Comment by diddledani** [comment]
I'm closing this issue, because it should be fixed. You didn't reply to my request for retesting, so if there is still an issue please reopen.
