### ISSUE TITLE
00-wsl2-systemd.sh: Permission denied

### ISSUE THREAD

**Issue by Christian-Rau** [diddledani/one-script-wsl2-systemd#8]
After running the script, and booting up distro (ubuntu-20.04 I get permission denied.

chmod on the 00-wsl2-systemd.sh says `-rw-r--r-- 1 root root`

Changed permission to chmod 0755 /etc/profile.d/00-wsl2-systemd.sh and the script ran.
Then when starting the distro I see a blinking curser, and at one point I found this error:
rm: cannot remove '/mnt/c/users/john/.ubuntu/doe/.systemd.env'

Errors when trying to reset with:
powershell.exe: ScriptBlock should only be specified as a value of the Command parameter.
or from within bash. Black screen.

I made 10 various attempts to figure out where the problem might be, but with no luck. such a shame..

**Comment by diddledan** [comment]
Did you run the script from the default branch here on GitHub, or from the `build-21286+` branch? Most development effort is focused on the latter, which is currently only suitable for the Insider Builds of Windows, so I might have left a broken copy in the main branch.

**Comment by Christian-Rau** [comment]
Yes I ran it from the default branch, I kind of suspected that might be the issue.

**Comment by diddledani** [comment]
Can you try again using the `main` branch. There have been several improvements, and it might be fixed now.

**Comment by diddledani** [comment]
You didn't reply to my request for a retest, so I'm going to close the issue as I think it is working correctly. Please reopen if there is still an issue.
